"""Initial migration

Revision ID: initial_migration
Revises:
Create Date: 2024-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'initial_migration'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(255), nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['parent_id'], ['categories.id']
                    ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'])
    op.create_index('ix_categories_name', 'categories', ['name'])

    op.create_table('clients',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(255), nullable=False),
                    sa.Column('address', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_clients_name', 'clients', ['name'])

    op.create_table('nomenclature',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(255), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Numeric(10, 2), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('top_category_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['categories.id']
                    ),
                    sa.ForeignKeyConstraint(
                        ['top_category_id'], ['categories.id']
                    ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_nomenclature_category_id', 'nomenclature', ['category_id'])
    op.create_index('ix_nomenclature_name', 'nomenclature', ['name'])
    op.create_index('ix_nomenclature_price', 'nomenclature', ['price'])
    op.create_index('ix_nomenclature_top_category_id', 'nomenclature', ['top_category_id'])

    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('client_id', sa.Integer(), nullable=False),
                    sa.Column('total_amount', sa.Numeric(12, 2), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['client_id'], ['clients.id']
                    ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_orders_client_id', 'orders', ['client_id'])
    op.create_index('ix_orders_created_at', 'orders', ['created_at'])

    op.create_table('order_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Numeric(10, 2), nullable=False),
                    sa.Column('total_price', sa.Numeric(12, 2), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['orders.id']
                    ),
                    sa.ForeignKeyConstraint(
                        ['nomenclature_id'], ['nomenclature.id']
                    ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'])
    op.create_index('ix_order_items_nomenclature_id', 'order_items', ['nomenclature_id'])
    op.create_index('ix_order_items_order_nomenclature', 'order_items', ['order_id', 'nomenclature_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_order_nomenclature', table_name='order_items')
    op.drop_index('ix_order_items_nomenclature_id', table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_client_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_nomenclature_top_category_id', table_name='nomenclature')
    op.drop_index('ix_nomenclature_price', table_name='nomenclature')
    op.drop_index('ix_nomenclature_name', table_name='nomenclature')
    op.drop_index('ix_nomenclature_category_id', table_name='nomenclature')
    op.drop_table('nomenclature')
    op.drop_index('ix_clients_name', table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
